# Generated by Django 2.2.5 on 2020-04-26 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasy_app', '0002_auto_20200425_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('players', models.ManyToManyField(through='user_team.UserPlayer', to='fantasy_app.Player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
    ]
