# Generated by Django 2.2.5 on 2020-04-26 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='players',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='total_points',
        ),
        migrations.AddField(
            model_name='userplayer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userplayer',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy_app.Player'),
        ),
        migrations.AlterField(
            model_name='userplayer',
            name='user_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_team.UserTeam'),
        ),
    ]
