# Generated by Django 2.2.5 on 2020-04-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_team', '0002_auto_20200426_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplayer',
            name='user_team',
        ),
    ]
