# Generated by Django 2.2.5 on 2020-04-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40)),
                ('slug', models.SlugField(unique=True)),
                ('home_city', models.CharField(max_length=40)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=40)),
                ('player_image', models.ImageField(upload_to='player/')),
                ('credit', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('designation', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=30)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='fantasy_app.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='fantasy_app.Team')),
            ],
        ),
    ]
