# Generated by Django 2.2.5 on 2020-04-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='designation',
            field=models.CharField(choices=[('WK', 'WicketKeeper'), ('BAT', 'Batsman'), ('BOWL', 'Bowler'), ('ALL', 'All Rounder')], max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
