# Generated by Django 2.2.5 on 2020-04-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_app', '0003_auto_20200426_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='designation',
            field=models.CharField(choices=[('W/K', 'WicketKeeper'), ('Bat', 'Batsman'), ('Bowl', 'Bowler'), ('All round', 'All Rounder')], max_length=30),
        ),
    ]
