# Generated by Django 2.2.5 on 2020-04-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_app', '0007_auto_20200427_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='shortform',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
